version: "2"

services:
  nodpicod:
    image: picoio/pico:v1.1.4
    build:
      context: .
      dockerfile: Dockerfile
      #args:
      #  branch: master

    command: /opt/picoio/bin/nodpicod.sh --verbose-http-errors --max-transaction-time=1000 --data-dir /opt/picoio/bin/data-dir -e --http-alias=nodpicod:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    hostname: nodpicod
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"

  kpicod:
    image: picoio/pico:v1.1.4
    command: /opt/picoio/bin/kpicod --wallet-dir /opt/picoio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=kpicod:8900 --http-alias=localhost:8900
    hostname: kpicod
    ports:
      - 8900:8900
    links:
      - nodpicod
